### PR TITLE
Changed variable syntax to be compatible with PHP7 in Varien_File_Upl…

### PR DESCRIPTION
**Pull request by marcoroest87**
see _validateFile(), line 274

### CODE REVIEW

**Comment by Den4ik** [comment]
_validateFile method moved to Mage_Core_Model_File_Uploader

**Comment by icurdinj** [comment]
Already fixed in another way. Doesn't need to be merged.

**Comment by marcoroest87** [comment]
I'm getting errors on this class using the latest version of the master branch (CE). How should this be resolved? 

We are running into this error with an external extension (not core functionality).

**Comment by icurdinj** [comment]
Fix the extension, obviously.

**Pull request closed without merging**
