### PR TITLE
Moves the module to the community code pool

### PR DESCRIPTION
**Pull request by azambon**
As the title says, extensions should be in the community code pool.
A similar modification would be needed for the 1.9.2.4 branch.

### CODE REVIEW

**Comment by ivanweiler** [comment]
Hello there, 

It's hard to decide what is better here since we're literally patching the core :) In ideal scenario that would be done by Magento in core pool and not by extension.

Extension was initially made for our own projects, so we used local to have rewrite and autoload priority (ofc). It was later released so Magento community can have a starting point to make their stores php 7 compatible.

But I agree that, at this point, community pool would probably allow easier customizations in local when/if needed.

We'll consider it for future release, but I think changing this now would make updates really confusing. And most developers that use it as a starting point can change pool and fork it anyway.

Regards

**Comment by azambon** [comment]
I did make this PR because I found a rewrite conflict on core/layout between this extension and another third party extension. And both of these install in the local code pool, so no luck trying to monkey patch one rewrite to make it extend the other.
In the end I solved it anyway (by defining a custom module that overrides both rewrites), but that's even less clean than a monkey patch IMHO.

**Comment by durzel** [comment]
What third party extension was it by the way, so others can avoid the same trap?

**Comment by azambon** [comment]
Peexl_DailyDeals ( https://www.peexl.com/magento-extensions/daily-deals.html )

**Pull request closed without merging**
