### PR TITLE
make file validation in uploader compatible to PHP7

### PR DESCRIPTION
**Pull request by arosenhagen**
error thrown: Uncaught Error: Function name must be a string in lib/Varien/File/Uploader.php:259
according to [Magento 1.9.2 and php7 - image upload error](https://magento.stackexchange.com/questions/93066/magento-1-9-2-and-php7-image-upload-error)

### CODE REVIEW

**Comment by icurdinj** [comment]
Inchoo_PHP7 solved that error a long time ago, rewriting classes which inherit from Varien_File_Uploader, so this is not needed.
Did you actually have a case where Magento core directly used Varien_File_Uploader and crashed, with Inchoo_PHP7 installed?

**Comment by rbrown** [comment]
I had this issue with avstudnitz/AvS_FastSimpleImport. When uploading a new product, _media_image was set to an http:// url, and the file didn't exist. In the [`_getUploader` function](https://github.com/avstudnitz/AvS_FastSimpleImport/blob/master/src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product.php#L1346) it directly instantiates `Mage_ImportExport_Model_Import_Uploader` 

The code in there is copied from `app/code/core/Mage/ImportExport/Model/Import/Uploader.php`

**Comment by icurdinj** [comment]
@rbrown it looks to me that avstudnitz/AvS_FastSimpleImport should be fixed then. This extension only updates Magento core for PHP 7 compatibility.

**Comment by rbrown** [comment]
Hi @icurdinj I disagree.  The AvS code is a copy of this method [_getUploader](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/ImportExport/Model/Import/Entity/Product.php#L1622) in `Mage_ImportExport_Model_Import_Entity_Product` (not Uploader.php like I originally said). So anyone using the Magento class (e.g. through the admin interface) will have the same issue.

I'm not sure why it's directly instantiating it, although the default constructor makes instantiating it weird. But without  patching it to `Mage::getModel('importexport/import_uploader', null)` the Inchoo Uploader will never be used instead. I also grepped the code, it looks like there's no other places that use Mage_ImportExport_Model_Import_Uploader

**Comment by icurdinj** [comment]
@rbrown : 
`Mage_ImportExport_Model_Import_Uploader extends Mage_Core_Model_File_Uploader`
which, in turn, **is** patched by Inchoo_PHP7, so anyone using the Magento class will have no issue.
I hope you understand there is no sane way for this extension to go around fixing other extensions PHP7 incompatibilities. I guess you should address your issue here: [https://github.com/avstudnitz/AvS_FastSimpleImport/issues](https://github.com/avstudnitz/AvS_FastSimpleImport/issues). In fact, since you already fixed it, you might make a pull request for them.

**Comment by rbrown** [comment]
Hi @icurdinj sorry to be a pest, I realise this is probably posted against the wrong pull request as this one is fixing the wrong thing, and also this is independent of AvS/FSI (it was just where I first encountered this), but to continue our discussion.

- `Mage_ImportExport_Model_Import_Uploader` extends `Mage_Core_Model_File_Uploader`
- This extension replaces the core `Mage_Core_Model_File_Uploader` with a version that has a `_validateFile` method
- The class [Mage_ImportExport_Model_Import_Uploader](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/ImportExport/Model/Import/Uploader.php#L119) also defines `_validateFile`  with incompatible PHP7 code
- `Mage_ImportExport_Model_Import_Uploader->_validateFile` also needs to replaced

**Comment by icurdinj** [comment]
And it is replaced already:
`Inchoo_PHP7_Model_Import_Uploader extends Mage_ImportExport_Model_Import_Uploader`

And in config.xml:
```
<importexport>
           <rewrite>
                    <import_uploader>Inchoo_PHP7_Model_Import_Uploader</import_uploader>
```

**Pull request closed without merging**
