### PR TITLE
fixed compatibility with Amasty_Orderattr

### PR DESCRIPTION
**Pull request by sprankhub**

### CODE REVIEW

**Comment by durzel** [comment]
Amasty ought to be installing their extensions into "community" rather than "local", but they aren't the only ones to do this.

Adding extension detection hacks into Inchoo_PHP7 is imo pretty janky.  It should be the extensions that are patched to work with Inchoo_PHP7, not the other way around, otherwise you could end up in a situation where you have a switch() statement to handle all of the different extensions that override Mage_Core_Helper_Data.

**Comment by sprankhub** [comment]
community vs. local code pool should not make any difference here.

I do not like these checks as well. But there IS a rewrite conflict between `Inchoo_PHP7` and `Amasty_Orderattr`. So what would be your suggestion to solve it?

**Comment by durzel** [comment]
I just mean if Amasty stuff was in community then you could override it yourself in local.

My point was that there are probably many other rewrite conflicts, in other extensions. Should Inchoo be patched (presumably with a switch statement) for all of these?

An alternative perhaps would be to maintain a list of third party incompatibilities, e.g. in the README.md ?

**Comment by sprankhub** [comment]
Ah now I understand. True.

I still think that a conditional rewrite is the best we can come up with in these cases. Stating that such extensions are simply not compatible is not a nice solution IMHO.

**Pull request closed without merging**
