### PR TITLE
Enterprise level changes

### PR DESCRIPTION
**Pull request by benjamw**
One more change on the enterprise level. Not sure if you want to make a new enterprise branch, or just include this in the master branch.

### CODE REVIEW

**Comment by benjamw** [comment]
Sorry, somehow this got the master branch changes as well... I can fix it if you want me to. Just let me know.

**Comment by icurdinj** [comment]
Sorry for the late reply! This looks EE specific, so it might be wise to make a separate branch and release... Please have a little more patience, I have to test this on EE, and find a good strategy for CE & EE releases...

**Comment by benjamw** [comment]
If it's any consolation, I'm using this on both EE and CE, and it seems to work fine on both. There are no errors reported on CE that it's trying to find any missing EE classes.

**Comment by icurdinj** [comment]
I just made a separate branch for EE. Could you please make a new pull request for this against the EE branch? Or maybe retarget this one, I'm not sure if that's possible.
(Even if it doesn't trigger errors on CE, it doesn't seem allright to push EE specific code to everyone. We'll make two separate releases.)

**Pull request closed without merging**
